cache: 
  paths:
    - node_nodules/

stages:
  - build
  - deploy

before_script: 
  - "docker login registry.gitlab.com -u $GITLAB_USER -p $GITLAB_PASS"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - "docker build -t registry.gitlab.com/shinasaki/studentclub-nbr ."
    - "docker push registry.gitlab.com/shinasaki/studentclub-nbr"
  only:
    - master

staging-deploy:
  stage: deploy
  script: 
    - echo 'staging deploy'
  environment:
    name: staging
    url: http://$APPS_DOMAIN
  only:
    - master

production-deploy:
  stage: deploy
  script:
    - rsync -av --delete public /srv/nginx/pages/$CI_BUILD_REF_SLU
  environment:
    name: production
    url: http://production.$APPS_DOMAIN
  when: manual
  only:
    - master
  when: manual