image: node:latest

cache: 
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - yarn
    - yarn run build
  only:
    - master

staging-deploy:
  stage: deploy
  script: 
    - rsync -hrvz --delete dist/ /srv/nginx/pages/staging
  environment:
    name: staging
    url: http://$APPS_DOMAIN
  only:
    - master

production-deploy:
  stage: deploy
  script:
    - rsync -av --delete dist/ /srv/nginx/pages/production
  environment:
    name: production
    url: http://production.$APPS_DOMAIN
  when: manual
  only:
    - master
  when: manual