build site:
  image: node:9
  stage: build
  tags: 
    - node
  script:
    - yarn install --progress=false
    - yarn run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit test:
  image: node:9
  stage: test
  tags:
    - node
  script:
    - yarn install --progress=false
    - yarn run unit

deploy:
  image: alpine
  stage: deploy
  tags: 
    - alpine
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ user@server.com:/your/project/path/