image: node:9

cache: 
  paths:
    - node_nodules/

stages:
  - build
  - staging
  - production

build:
  stage: build
  script:
    - echo start building...
    - yarn install --progress=false
    - yarn run build
  only:
    - master

staging:
  stage: staging
  script: 
    - rsync -av --delete public /srv/nginx/pages/$CI_BUILD_REF_SLU
  environment:
    name: staging
    url: http://$APPS_DOMAIN
  only:
    - master

production:
  stage: production
  script:
    - rsync -av --delete public /srv/nginx/pages/$CI_BUILD_REF_SLU
  environment:
    name: production
    url: http://production.$APPS_DOMAIN
  when: manual
  only:
    - master