version: "3"

services:


  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
        - /var/data:/data/db
    ports:
       - 27017:27017

  nginx:
    image: nginx:1.14-alpine
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes: 
      - /etc/ssl:/etc/ssl
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist/:/var/www/html/

  backend:
    container_name: backend
    restart: always
    build: ../studentclub-nbr-backend
    ports:
      - 3000:3000

  
