version: "3"

services:

  nginx:
    image: nginx:1.14-alpine
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes: 
      - /etc/ssl:/etc/ssl
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/default.conf:/etc/nginx/sites-available/nbr.ac.th
      - ./:/var/www/nbr.ac.th/html

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
        - /var/data:/data/db
    ports:
       - 27017:27017
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:27017"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    container_name: backend
    build: ../studentclub-nbr-backend
    restart: always
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - ./dist/static/clubs:/clubs

  
