version: "3"

services:

  nginx:
    image: nginx:1.14-alpine
    networks:
      - studentclub
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes: 
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/ssl:/etc/ssl
      - ./web:/web

  app:
    container_name: app
    build: .
    networks:
      - studentclub
    restart: always
    ports:
      - 80:80
      - 443:443

  mongo:
    container_name: mongo
    image: mongo
    networks:
      - studentclub
    restart: always
    volumes:
        - ./data:/data/db
    ports:
       - 27017:27017

  
