version: "3"

services:

  nginx:
    image: nginx:1.14-alpine
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes: 
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/ssl:/etc/ssl
      - ./web:/web

  frontend:
    container_name: frontend
    build: .
    restart: always
    ports:
      - 80:80

  backend:
    container_name: backend
    build: ../studentclub-nbr-backend
    restart: always
    ports:
      - 3000:3000

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
        - ./data:/data/db
    ports:
       - 27017:27017

  
