version: "3"

services:

  nginx:
    image: nginx:1.14-alpine
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes: 
      - /etc/ssl:/etc/ssl
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist /usr/share/nginx/html
  
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
        - /var/data:/data/db
    ports:
       - 27017:27017

  frontend:
    container_name: frontend
    build: .
    restart: always

  backend:
    container_name: backend
    build: ../studentclub-nbr-backend
    restart: always
    ports:
      - 3000:3000

  
